package key

var KEY_QUERY_FIELDS = "fields"
var KEY_QUERY_LINK = "link"
var KEY_QUERY_WHERE = "where"
var KEY_QUERY_SEARCH = "search"
var KEY_QUERY_PAGEINDEX = "index"
var KEY_QUERY_PAGESIZE = "size"
var KEY_QUERY_ORDER = "order"
var KEY_CACHE = "cacheKey"
var ASYNC_KEY = "asyncKey"
var TABLE_NAME = "tableName"
var GROUP_FUNC = "groupFunc"
var GROUP_BY="groupFields"
var IMPORT_TEMPLATE_KEY="importKey"
var FUNC_KEY="FuncKey"